version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: superpassword
      MYSQL_ROOT_PASSWORD: superrootpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
        - ./storage/app/public:/var/www/html/public/storage
        - ./storage:/var/www/html/storage
        - ./.env:/var/www/html/.env
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "9000:9000"
    networks:
        - laravel
    depends_on:
        - mysql
    command: >
        sh -c "php artisan key:generate && php artisan migrate:fresh --seed && exec php-fpm"
